- input4MIPs_source_id.json
- src/getInput4MIPsESGF.ipynb
> adding MRI-JRA55-do-1-6-0 from ESGF index

- docs/cvs_guidance.md
- input4MIPs_institution_id.json
- input4MIPs_source_id_zn_1.json
- input4MIPs_source_id_zn_2.json
> Add GHG concentrations registration

- input4MIPs_source_id.json
- src/registerSource_id.ipynb
> register DRES-CMIP-BB4CMIP7-1-0 (#10)

- input4MIPs_source_id.json
- src/registerSource_id.ipynb
> tweaks to VUA-CMIP-BB4CMIP6 entries (#10)

- input4MIPs_source_id.json
- src/registerSource_id.ipynb
> tweaks to UReading-CCMI dataset entries (#16)

- input4MIPs_source_id.json
- src/registerSource_id.ipynb
Fixing up missing entries, "title" was omitted from new registrations
> validate entries

- CITATION.cff
- docs/input4MIPs_source_id.html
- src/jsonToHtml.py
> update HTML with active download links (#33)

- scripts/pollESGF.py
Fix #48 
@znichollscr this will not work for you, yet - need to whitelist nimbus
> add ESGF index scour (#48)

- CVs/input4MIPs_source_id.json
Closes #42 
Waiting for confirmation in #42 before being ready for review
> Add biomass burning source ID info

- README.md
- scripts/pollESGF.py
Fix #52 
@znichollscr wanna peek and merge?
> Issue52 durack1 contribution sync tweaks

- README.md
- docs/input4MIPs_datasets_CMIP6Plus.html
- docs/input4MIPs_files_CMIP6Plus.html
- scripts/database-interactions/Makefile
- scripts/database-interactions/generate-html-pages.py
@durack1 over to you to make sure you can run the scripts and bump to whatever version you want next.
> Add version flag to CLI

- README.md
- changelog/74.docs.md
> Hot fix README

- CVs/input4MIPs_target_mip.json
- changelog/78.breaking.md
> Remove use of confusing name

- changelog/79.docs.md
- docs/input4MIPs_files_CMIP6Plus.html
- python-packages/input4MIPs-CVs/src/input4MIPs_CVs/html_generation.py
> Only show actual files in files view

- Database/input4MIPs_db_file_entries.json
- changelog/81.trivial.md
- docs/input4MIPs_datasets_CMIP6Plus.html
- python-packages/input4MIPs-CVs/src/input4MIPs_CVs/cli/update-database.py
> Update status of files in publication queue

- changelog/92.docs.md
- docs/input4MIPs_source-id_CMIP6Plus.html
- python-packages/input4MIPs-CVs/src/input4MIPs_CVs/html_generation.py
> Add source ID level HTML view

- changelog/69.trivial.md
- scripts/pollESGF.py
There is a need to automate the querying of the ESGF input4MIPs index, this code queries the index, but needs to be automated on a cronjob to remove an additional manual test
Fix #69
> Issue69 durack1 automate ESGF scrape

- changelog/103.trivial.md
- python-packages/input4MIPs-CVs/src/input4MIPs_CVs/db_changes.py
> Make comment generation more robust

- changelog/94.fix.md
- changelog/94.trivial.md
My turn for some pedantry, just updating the CHANGELOG entry.
> Tweak CHANGELOG entry

- README.md
- changelog/106.trivial.md
> Hot fix README docs badge

- README.md
- changelog/107.trivial.md
Correcting some HTML link loose ends. Cleanup redundant headers in README.md
Fix #107
> update README, correct HTML links, cleanup

- changelog/111.docs.md
- docs/database-views/index.md
- docs/database-views/input4MIPs_datasets_CMIP6Plus.html
- docs/database-views/input4MIPs_delivery-summary_CMIP6Plus.html
- docs/database-views/input4MIPs_files_CMIP6Plus.html
- docs/database-views/input4MIPs_source-id_CMIP6Plus.html
- mkdocs.yml
- python-packages/input4MIPs-CVs/src/input4MIPs_CVs/html_generation.py
Nowhere near as pretty as what is currently on https://wcrp-cmip.org/cmip7-task-teams/forcings/, but might be easier to maintain while we wait for a front-end interested person.
> Add delivery summary view

- changelog/129.trivial.md
- scripts/createDRS.py
Trivial fix adding tests to catch missing/incorrect global attributes
> update createDRS.py to catch issues (#37)

- changelog/130.trivial.md
- scripts/createDRS.py
A couple of tweaks to get tracking_id checking working across a complete dataset (multiple files). Ref #37
> updated to include license - absEssAttList (#37)

- changelog/132.docs.md
- docs/database-views/input4MIPs_datasets_CMIP6Plus.html
- docs/database-views/input4MIPs_delivery-summary_CMIP6Plus.html
- docs/database-views/input4MIPs_files_CMIP6Plus.html
- docs/database-views/input4MIPs_source-id_CMIP6Plus.html
- python-packages/input4MIPs-CVs/src/input4MIPs_CVs/html_generation.py
> Add placeholder for population dataset

- .github/workflows/ci.yaml
- changelog/145.trivial.md
- docs/contributing.md
- scripts/load-cvs-with-input4mips-validation.py
> Add check that CVs load to CI

- changelog/148.docs.md
- docs/database-views/input4MIPs_delivery-summary_CMIP6Plus.html
- python-packages/input4MIPs-CVs/src/input4MIPs_CVs/html_generation.py
> Update CEDS delivery date

- changelog/151.docs.md
- docs/contributing.md
- docs/dataset-overviews/aerosol-optical-properties-macv2-sp.md
- docs/dataset-overviews/amip-sst-sea-ice-boundary-forcing.md
- docs/dataset-overviews/anthropogenic-slcf-co2-emissions.md
- docs/dataset-overviews/cmip7_phases_source_ids.csv
- docs/dataset-overviews/co2-isotopes.md
- docs/dataset-overviews/fill-out-auto-generated-sections.py
- docs/dataset-overviews/greenhouse-gas-concentrations.md
- docs/dataset-overviews/index.md
- docs/dataset-overviews/land-use.md
- docs/dataset-overviews/nitrogen-deposition.md
- docs/dataset-overviews/open-biomass-burning-emissions.md
- docs/dataset-overviews/ozone.md
- docs/dataset-overviews/population.md
- docs/dataset-overviews/solar.md
- docs/dataset-overviews/stratospheric-volcanic-so2-emissions-aod.md
- docs/dataset-overviews/write-revision-history.py
- mkdocs.yml
> Add source IDs for use in various CMIP7 phases

- changelog/160.docs.md
- changelog/160.trivial.md
- docs/database-views/input4MIPs_datasets_CMIP6Plus.html
- docs/database-views/input4MIPs_delivery-summary_CMIP6Plus.html
- docs/database-views/input4MIPs_source-id_CMIP6Plus.html
- docs/dataset-overviews/aerosol-optical-properties-macv2-sp.md
- docs/dataset-overviews/amip-sst-sea-ice-boundary-forcing.md
- docs/dataset-overviews/anthropogenic-slcf-co2-emissions.md
- docs/dataset-overviews/co2-isotopes.md
- docs/dataset-overviews/greenhouse-gas-concentrations.md
- docs/dataset-overviews/land-use.md
- docs/dataset-overviews/nitrogen-deposition.md
- docs/dataset-overviews/open-biomass-burning-emissions.md
- docs/dataset-overviews/ozone.md
- docs/dataset-overviews/population.md
- docs/dataset-overviews/solar.md
- docs/dataset-overviews/stratospheric-volcanic-so2-emissions-aod.md
- python-packages/input4MIPs-CVs/src/input4MIPs_CVs/html_generation.py
> Cross-reference summary in docs

- changelog/167.docs.md
- docs/database-views/input4MIPs_delivery-summary_CMIP6Plus.html
- python-packages/input4MIPs-CVs/src/input4MIPs_CVs/html_generation.py
> Fix up CEDS delivery summary

- changelog/170.docs.md
- docs/database-views/input4MIPs_delivery-summary_CMIP6Plus.html
- python-packages/input4MIPs-CVs/src/input4MIPs_CVs/html_generation.py
> Update delivery summary info for simple plumes

- changelog/169.docs.md
~- [ ] (N/A) Documentation added (where applicable)~
> Add missing CHANGELOG entry

- Database/input-data/supplementary-source-id-info.yaml
- changelog/185.trivial.md
- docs/contributing.md
- docs/database-views/input4MIPs_datasets_CMIP6Plus.html
- docs/database-views/input4MIPs_source-id_CMIP6Plus.html
- docs/dataset-overviews/greenhouse-gas-concentrations.md
- python-packages/input4MIPs-CVs/pyproject.toml
- python-packages/input4MIPs-CVs/src/input4MIPs_CVs/cli/update-database.py
> Split supplementary info into a clearer spot

- .github/ISSUE_TEMPLATE/data_issue.md
- changelog/190.trivial.md
> Add issue template

- changelog/193.docs.md
- docs/changelog.md
- docs/dataset-overviews/fill-out-auto-generated-sections.py
- docs/dataset-overviews/index.md
> Fix minor bugs in the docs

- CVs/input4MIPs_source_id.json
- changelog/195.feature.md
- changelog/195.improvement.md
- python-packages/input4MIPs-CVs/src/input4MIPs_CVs/cli/update-database.py
Not an ideal solution as we now have duplicate data, but we will be able to break this out later as needed so just rolling with this for now.
This is needed for #177 so there is something machine parsable with which to create DOIs.
> Add author field

- CVs/input4MIPs_source_id.json
- changelog/198.fix.md
> Fix up incorrect mip era target for latest solar

- Database/input-data/supplementary-source-id-info.yaml
- changelog/205.docs.md
- changelog/205.fix.md
- docs/database-views/input4MIPs_datasets_CMIP6Plus.html
- docs/database-views/input4MIPs_datasets_CMIP7.html
- docs/database-views/input4MIPs_files_CMIP7.html
- docs/database-views/input4MIPs_source-id_CMIP6Plus.html
- docs/database-views/input4MIPs_source-id_CMIP7.html
- python-packages/input4MIPs-CVs/src/input4MIPs_CVs/html_generation.py
> Fix up DOIs and show them in DB views

- .github/pull_request_template.md
- changelog/217.docs.md
- changelog/217.trivial.md
- docs/dataset-overviews/stratospheric-volcanic-so2-emissions-aod.md
> Update volcanic documentation and PR template

- README.md
- changelog/206.docs.md
> Clean up README

- Database/input-data/pmount/13a5ef17ce5967fc857184ffcfd43076671080c3768a303e5b663a84bc2caa0d.json
- Database/input-data/pmount/3b2da71448f9eec95e9401179f33b215a374382e0d53e201bc7bbc73c7eb0ffd.json
- Database/input-data/pmount/50292b11299bafa755091912b0e9a50fb58c7eb8fc5b5b739b31f8b938a3ccfd.json
- Database/input-data/pmount/b01c2638a7a33ecf413997b73dfeeb9bb8eac0b97d63db22fa86add0e5b395b3.json
- Database/input-data/pmount/c4bd86833353c783336f4334621da09f74d531afdfd7e53c6bf447ee19693a65.json
- Database/input-data/pmount/dc538f995c06d66cfc0b2fc1190921ccfd26c2bc6e446762967117b18bfef98c.json
- Database/input-data/pmount/e7ea2967c30f0cc6fb1d82fa6131638f6813561fd8583e55f6ae4df1abe81d71.json
- Database/input-data/pmount/e939b49b252f45c5ec02a8489684aa0dcd3c3a00eb71ef1e2a22eda5345803ac.json
- changelog/230.fix.md
- docs/dataset-overviews/anthropogenic-slcf-co2-emissions.md
- docs/dataset-overviews/fill-out-auto-generated-sections.py
> Update CEDS file publication version

- .github/workflows/ci.yaml
- changelog/233.trivial.md
> Ignore checking of flaky globalfiredata.org in CI

- changelog/236.docs.md
- docs/dataset-overviews/greenhouse-gas-concentrations.md
> Update GHG conc docs

- changelog/232.docs.md
- docs/dataset-overviews/solar.md
> Update solar docs

- changelog/234.docs.md
- docs/dataset-overviews/stratospheric-volcanic-so2-emissions-aod.md
> Update volcanic forcing docs

- .github/workflows/ci.yaml
- changelog/245.docs.md
- docs/database-views/input4MIPs_delivery-summary.html
- docs/database-views/input4MIPs_delivery-summary_CMIP6Plus.html
- docs/dataset-info/delivery-summary.json
> Update delivery summary source IDs for CEDS

- changelog/254.breaking.md
- docs/database-views/input4MIPs_datasets_CMIP6Plus.html
- docs/database-views/input4MIPs_source-id_CMIP6Plus.html
> Update ESGF scrape

- changelog/277.trivial.md
- python-packages/input4MIPs-CVs/src/input4MIPs_CVs/cli/update-esgf-scrape.py
Seeing lots of failures with current set up: https://github.com/PCMDI/input4MIPs_CVs/actions/workflows/update-esgf-scrape.yaml
Adding an extra code on which to retry, seems to work: [PCMDI/input4MIPs_CVs/actions/runs/16255793397/job/45891890620](https://github.com/PCMDI/input4MIPs_CVs/actions/runs/16255793397/job/45891890620)
> Add more retries

- .github/workflows/update-esgf-scrape.yaml
- changelog/301.trivial.md
> Slowdown scrape frequency

- CVs/input4MIPs_source_id.json
- changelog/330.trivial.md
- docs/contributing.md
- docs/source-id-landing-pages/PIK-CMIP-1-0-0.json
- docs/source-id-landing-pages/PIK-CMIP-1-0-0.md
This PR supercedes #328 - with esgf-scrape, database and HTML pages updated
> Update PIK-CMIP-1-0-0 ORCID entry

- CVs/input4MIPs_source_id.json
- Database/input-data/supplementary-source-id-info.yaml
- changelog/317.trivial.md
- docs/database-views/input4MIPs_datasets_CMIP7.html
- docs/database-views/input4MIPs_source-id_CMIP7.html
- docs/source-id-landing-pages/DRES-CMIP-BB4CMIP7-2-1.json
- docs/source-id-landing-pages/PCMDI-AMIP-1-1-10.json
- docs/source-id-landing-pages/PCMDI-AMIP-1-1-10.md
- docs/source-id-landing-pages/PCMDI-AMIP-1-1-9.json
- docs/source-id-landing-pages/PCMDI-AMIP-1-1-9.md
- docs/source-id-landing-pages/UOEXETER-CMIP-2-2-1.json
- scripts/amendExistingSource_id.ipynb
- scripts/registerNewSource_id.ipynb
This PR cleans up some entries that are being written as prototype data to replace PCMDI-AMIP-1-1-10 in time, using datastreams that are temporally extended to near real-time. These are being tested in E3SM-2-0 AMIP configurations to see how simulations compare to earlier PCMDI-AMIP-1-1-9 and earlier boundary conditions.
A couple of DOI assignment catchups and cleanups also embedded here, along with a database and HTML update.
@znichollscr please review
Fix #317 
> Revise PCMDI-AMIP-* and prototype data; catchup on DOI assignments

- changelog/333.fix.md
- docs/database-views/input4MIPs_delivery-summary.html
- docs/dataset-info/delivery-summary.json
> Fix up docs about status of simple plumes datasets

- CVs/input4MIPs_source_id.json
- changelog/345.fix.md
> Add extra author to ozone and nitrogen source IDs
